### ISSUE TITLE
DROL-FC test error

### ISSUE THREAD

**Issue by buyudtx** [shallowtoil/DROL#14]
Traceback (most recent call last):
  File "test.py", line 261, in <module>
    main()
  File "test.py", line 189, in main
    outputs = tracker.track(img)
  File "../pysot/tracker/siamfc_tracker.py", line 182, in track
    self.classifier.update(bbox, flag)
TypeError: update() missing 1 required positional argument: 'flag'

**Comment by laisimiao** [comment]
Yes, I also find this bug.
In 
https://github.com/shallowtoil/DROL/blob/4aebe575394bc035e9924c8711c7d5d76bfef37a/pysot/tracker/siamfc_tracker.py#L181-L182
but its signature is: 
https://github.com/shallowtoil/DROL/blob/4aebe575394bc035e9924c8711c7d5d76bfef37a/pysot/tracker/classifier/base_classifier.py#L191-L195
